//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFrameworkCore.Resources.Partners {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestFrameworkCore.Resources.Partners.PartnerData", typeof(PartnerData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string CHNumber {
            get {
                return ResourceManager.GetString("CHNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coventry.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Midlands.
        /// </summary>
        internal static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supercoffee@coventrycoffee.com.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2112.
        /// </summary>
        internal static string HECentralGovOrgCode {
            get {
                return ResourceManager.GetString("HECentralGovOrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 852.
        /// </summary>
        internal static string HECombAuthCode {
            get {
                return ResourceManager.GetString("HECombAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string KeyAccount {
            get {
                return ResourceManager.GetString("KeyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex.
        /// </summary>
        internal static string KeyAccountManager {
            get {
                return ResourceManager.GetString("KeyAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 987.
        /// </summary>
        internal static string LocalAuthCode {
            get {
                return ResourceManager.GetString("LocalAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Limited.
        /// </summary>
        internal static string ParentPartner {
            get {
                return ResourceManager.GetString("ParentPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Institution.
        /// </summary>
        internal static string PartnerType {
            get {
                return ResourceManager.GetString("PartnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0123456789.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West Midlands.
        /// </summary>
        internal static string PrimaryOpRegion {
            get {
                return ResourceManager.GetString("PrimaryOpRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string SMEIndicator {
            get {
                return ResourceManager.GetString("SMEIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10003.
        /// </summary>
        internal static string SocHPRegNum {
            get {
                return ResourceManager.GetString("SocHPRegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friargate Lane.
        /// </summary>
        internal static string StreetThree {
            get {
                return ResourceManager.GetString("StreetThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friargate.
        /// </summary>
        internal static string StreetTwo {
            get {
                return ResourceManager.GetString("StreetTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Limited.
        /// </summary>
        internal static string UltParent {
            get {
                return ResourceManager.GetString("UltParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coffee1.co.uk.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
